name: Docker Image for dotcom

on:
  push:
    branches: ['develop', 'main']

env:
  REGISTRY: ghcr.io
  ACTOR: ${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.repository }}
  GIT_SHA: ${{ github.sha }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - uses: docker/build-push-action@v6
        with:
          context: ./
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_HASH=${{ env.GIT_SHA }}
            NEXT_PUBLIC_WEB_HOST=${{ github.ref_name == 'develop' && 'https://dev.schaechinger.com' || '' }}
